# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vision_pb2 as vision__pb2


class VisionStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.capture = channel.unary_unary(
                '/vision.Vision/capture',
                request_serializer=vision__pb2.visionRequest.SerializeToString,
                response_deserializer=vision__pb2.visionReply.FromString,
                )


class VisionServicer(object):
    """The greeting service definition.
    """

    def capture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'capture': grpc.unary_unary_rpc_method_handler(
                    servicer.capture,
                    request_deserializer=vision__pb2.visionRequest.FromString,
                    response_serializer=vision__pb2.visionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vision.Vision', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Vision(object):
    """The greeting service definition.
    """

    @staticmethod
    def capture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vision.Vision/capture',
            vision__pb2.visionRequest.SerializeToString,
            vision__pb2.visionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
