# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vision.proto',
  package='vision',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cvision.proto\x12\x06vision\"\x0f\n\rvisionRequest\"+\n\x0bvisionReply\x12\x0b\n\x03img\x18\x01 \x01(\x0c\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\x41\n\x06Vision\x12\x37\n\x07\x63\x61pture\x12\x15.vision.visionRequest\x1a\x13.vision.visionReply\"\x00\x62\x06proto3'
)




_VISIONREQUEST = _descriptor.Descriptor(
  name='visionRequest',
  full_name='vision.visionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=39,
)


_VISIONREPLY = _descriptor.Descriptor(
  name='visionReply',
  full_name='vision.visionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='vision.visionReply.img', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='vision.visionReply.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['visionRequest'] = _VISIONREQUEST
DESCRIPTOR.message_types_by_name['visionReply'] = _VISIONREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

visionRequest = _reflection.GeneratedProtocolMessageType('visionRequest', (_message.Message,), {
  'DESCRIPTOR' : _VISIONREQUEST,
  '__module__' : 'vision_pb2'
  # @@protoc_insertion_point(class_scope:vision.visionRequest)
  })
_sym_db.RegisterMessage(visionRequest)

visionReply = _reflection.GeneratedProtocolMessageType('visionReply', (_message.Message,), {
  'DESCRIPTOR' : _VISIONREPLY,
  '__module__' : 'vision_pb2'
  # @@protoc_insertion_point(class_scope:vision.visionReply)
  })
_sym_db.RegisterMessage(visionReply)



_VISION = _descriptor.ServiceDescriptor(
  name='Vision',
  full_name='vision.Vision',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=86,
  serialized_end=151,
  methods=[
  _descriptor.MethodDescriptor(
    name='capture',
    full_name='vision.Vision.capture',
    index=0,
    containing_service=None,
    input_type=_VISIONREQUEST,
    output_type=_VISIONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VISION)

DESCRIPTOR.services_by_name['Vision'] = _VISION

# @@protoc_insertion_point(module_scope)
